name: Tomorrow Prayer Times Daily Update

on:
  schedule:
    # Schedule to run daily at 10:30 AM UTC (5:30 AM Toronto time)
    - cron: '30 10 * * *'

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full commit history is fetched

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run scraper.py
      - name: Run Scraper
        run: |
          source .venv/bin/activate
          python python_scripts/scraper.py

      # Step 5: Configure Git and Commit Changes
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data/prayer_times/tomorrow_prayer_times.csv
          git commit --amend --no-edit
          git push -f
